### ISSUE TITLE
Rebus deserialization issue

### ISSUE THREAD

**Issue by DuleDimitrov123** [rebus-org/Rebus.RabbitMq#116]
Hi, 

I am using dotnet [CAP library][1] for publishing events (because I want outbox pattern) and Rebus for reading events from RabbitMQ (works perfectly with CAP and RabbitMQ.Client libraries). 

The problem is with serialization of the message in Rebus.

When I don't explicitly configure serializer (looks like System.Text.Json is default) the exceptions ocures that returnType (for serialization) is null (detailed exception in my first comment).

When I use NewtonsoftJson exception about not dispatching to any handlers (detailed exception in my first comment).

When I specify my explicit serializer it works, but I would like to avoid using it since I would like other system to be able to use my event without explicit definition of serializer (detailed exception and setup in my first comment).

Tried with couple of versions, same problem, but curently using Rebus with version 8.2.2 and dotnet 8.

My configuration:

```
...(other nonRebus setup)
 services.AddRebus(configure => configure
    .Transport(c =>
    {
        c.UseRabbitMq(rabbitMqConfig.ConnectionString, rabbitMqConfig.QueueName)
            .InputQueueOptions(o =>
            {
                o.SetAutoDelete(false);
                o.AddArgument("x-message-ttl", rabbitMqConfig.TimeToLive);
            });
    })
    	//.Serialization(s => s.Register(c => new CustomJsonSerializer())));
	    //.Serialization(s => s.UseNewtonsoftJson()));

services.AutoRegisterHandlersFromAssemblyOf<MyEventHandler>();

var bus = services.BuildServiceProvider().GetRequiredService<IBus>();
await bus.Subscribe<MyEvent>();
...(other nonRebus setup)
```

and my (testing) handler:

```
public class MyEventHandler : IHandleMessages<MyEvent>
{
    public Task Handle(MyEvent message)
    {
        Console.WriteLine("IT WORKS");

        return Task.CompletedTask;
    }
}
```

  [1]: https://github.com/dotnetcore/CAP

**Comment by mookid8000** [comment]
Rebus' built-in JSON serializers both need the `rbs2-msg-type` header to contain a value that allows the receiver to look up the .NET type and pass it as a parameter when deserializing.

From the error you're seeing, it looks like the type lookup returned NULL, which most likely means that the receiver does not have access to the .NET type mentioned in the header.

Please ensure that the `rbs2-msg-type` header has a value that gives a proper result when `Type.GetType(value)` gets called, or implement an alternative strategy by registering your own `IMessageTypeNameConvention`.

One way of easily customizing the type names is to use Rebus' built-in type name customizer, which can e.g. be used like this:

```csharp
services.AddRebus(
    configure => configure
        (...)
        .Serialization(s => s.UseCustomMessageTypeNames()
            .AddWithShortNames(new[] { typeof(string) }))
);
```


(in this case using short class names like "MyEvent" instead of the default "short, assembly-qualified type names")
