### ISSUE TITLE
Handle Events by name

### ISSUE THREAD

**Issue by arielmoraes** [rebus-org/Rebus.RabbitMq#28]
@mookid8000 answered my SO [question](https://stackoverflow.com/questions/51530523/how-to-subscribe-to-events-without-coupling-the-event-type-from-another-project/51541339#51541339) about how to keep message references decoupled by using custom topic names, but when the pipeline tries to deserialize the incoming message body the expected type to find the handlers is `Newtonsoft.Json.Linq.JObject`. Is there a way to replace the native implementation that Rebus uses to find the IHandleMessages to use the name of the Event instead of the type?

**Comment by mookid8000** [comment]
It's up to the serializer to take the incoming message and represent it as something meaningful, which usually happens by looking up a C# class with the type as specified by the `rbs2-msg-type` header.

When the type specified in the header cannot be found, it will fall back to deserializing the message as a `JObject`, which makes it possible to handle any type of message by creating a handler that implements `IHandleMessages<JObject>`, which can then peek around in the JSON object.

If that's not what you want, I suggest you either a) share a DLL with your message types, so that subscriber can deserialize into a proper class, or b) [inject an incoming pipeline step](https://github.com/rebus-org/Rebus/wiki/Extensibility#pipelines) that takes that `JObject` and turns it into something else, or c) replace the serializer alltogether, which will then give you the opportunity to basically do whatever you want 😁 

Let me know if this is not clear to you 😄

**Comment by arielmoraes** [comment]
Just saw I posted this question on the RabbitMq repo, sorry for that.

**Comment by mookid8000** [comment]
@arielmoraes good to hear you made it work 😄 and thanks for sharing your code!

> Just saw I posted this question on the RabbitMq repo, sorry for that.

I didn't even notice that, so I guess it's ok 😁
