### ISSUE TITLE
Throughput 10 times slower than RabbitMQ.Client

### ISSUE THREAD

**Issue by iustin94** [rebus-org/Rebus.RabbitMq#4]
Hi, 

I hope this is relevant. I made some publishing to a RabbitMQ server to test out the performance of Rebus compared to RabbitMQ.Client library. I found that for my setup the Publisher that was not using Rebus was publishing approximately 1,600 msg/s. Publishing with the simplest Rebus configuration only managed to do 130-150 msg/s. Is this throughput tax normal given all the abstraction Rebus ads? It seems that publishing 10 times slower is too much of a performance problem. 

I uploaded the 2 publishing console applications to github (https://github.com/iustin94/RabbitMQ-Benchmarker). 

Thanks!

**Comment by mookid8000** [comment]
Rebus definitely adds some overhead compared to using the RabbitMQ driver directly, so you will probably never be able to get those two numbers to be equal or even close to each other.

Your benchmarking code does suffer slightly from 🍎  and 🍊  comparison syndrome though, as Rebus always 

* creates durable queues (meaning that RabbitMQ persists messages on disk and does not lose them if it crashes hard)
* uses an exchange (default `RebusDirect`) even for point-to-point messaging
* passes the `x-ha-policy=all` option when declaring the queue allowing it to work in high availability clusters
* serializes the sent message (by default using Newtonsoft JSON.NET)
* enlists in am ambient Rebus handler transaction (if one exists) to buffer outgoing messages to be sent AFTER your Rebus handler has finished executing

and more 😄 

I suggest you think about your requirements, both functional and non-functional, and then figure out which solution brings the best balance between features and raw performance.

One guideline I can give you is this: Everything in Rebus revolves around _durable messages_, meaning that the messages in the queues are just as important as the data in your database. Therefore, Rebus will make it almost impossible for you to lose a message, no matter how hard you try 😉 

If you really need to publish 1000s of messages per second, my guess is that either

a) the messages are too granular, i.e. they could benefit from packing 10 or 100 of whichever thing they represent into one slightly chunkier message, or
b) the messages are not that important, i.e. the information they represent is easily replaced by possible later pieces of information (meaning that you should probably not use a durable transport for this type of message)

I hope this makes sense to you – feel free to tell me more about your requirements, and then I can help you figure out if Rebus is a good match or not.

I often tell people to use something else instead of Rebus in cases where I do not think it is a good fit for them. Everyone is happier that way 😁

**Comment by mookid8000** [comment]
btw with Rebus you should ALWAYS either `await` the task returned by Rebus' asynchronous API like this:

    await bus.Send(yourMessage);

or 

    bus.Advanced.SyncBus.Send(yourMessage);

if you are not in an asynchronous context (e.g. deep in a call hierarchy, possibly in ASP.NET, etc.)

I don't think it really makes a difference in your benchmarking code though, as the RabbitMQ client does not have a `Task`-based asynchronous API, and thus ends up executing everything synchronously even though it is not awaited.

**Comment by iustin94** [comment]
Hei, thank's for all the in depth info 😄 

My intention is to use Rebus for a web based solution where RabbitMQ acts as the intermediary between solution layers and logical components. The components/microservices that I intend to use can be replicated to boost up throughput of the system. One thing I've noticed with the RebusWorker that I linked above was that, if on the same machine I started N workers, then the message rate will go up N times without affecting the processor. Because of this I was thinking that I configured something wrong since one instance with the Rebus was not using the full processing power it has available to itself.

As per my solution requirements, the messages are very important and can't really afford to lose any. Given this requirement, horizontal scaling is a must to boost throughput in critical periods while also maintaining the persistence aspect of it which is also necessary but resource demanding. 

I did notice that the incoming message rates is the same as the disk write rates in rebus, while in RabbitMQ.client even tho I set the messages to be persistent, they exhibit a transient like behavior where they only get written to disk when the memory sets off an alarm. Could you mention how did you configure the library to have every message published, immediately written to disk?

**Comment by mookid8000** [comment]
Hmm I think it might be [this line](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/RabbitMq/RabbitMqTransport.cs#L464) that does the trick by setting the `Persistent` props value to `true`

**Comment by iustin94** [comment]
I didn't get the same behavior with just setting persistence enabled. I had to also pass these arguments to the **channel.QueueDeclare** method. 
` Dictionary<String, object> arguments = new Dictionary<String, Object>();
                arguments.Add("x-queue-mode", "lazy");`

I thought the disk writing would have a big impact and would explain the lower throughput with rebus, but I still get 1500+ publishes.

**Comment by mookid8000** [comment]
Durable messages with RabbitMQ requires two things – 1: you must declare the queue to be durable (which is an option on the `QueueDeclare` method), and 2: you must set the `Persistent` flag on the props on each message.

My understanding of `x-queue-mode` = `lazy` is that it simply tells RabbitMQ that it should not in-mem cache the messages so aggressively, because the queue in question can be very long possibly for a long time. I am guessing that this will make RabbitMQ use the disk for storage, even though it might not be guaranteed to be durable.
