### ISSUE TITLE
Fixing queue TTL functionality

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus.RabbitMq#55]
Long ago, I submitted changes to allow queue ttl so we could auto expire queues that no longer had any subscribers (after a certain amount of time)
https://github.com/rebus-org/Rebus.RabbitMq/pull/43

I've since done a bit of research, as I've noticed that queue's are always destroyed the moment subscribers are disconnected (regardless of any queue-ttl). I'm trying to determine definitively whether this is happening at the rabbitmq level (bug, or mishandling of queue declare properties) or perhaps something specific to Rebus.RabbitMQ.

Is it possible Rebus is deleting the queue external to the flag on the queue declare? Upon subscribers disconnecting? (Eg, should it be deleting queues with no subscriber on disconnect and that we just need to provide an additional check to see if any TTL was provided?)

According to rabbitmq admin, it looks like it does set autodelete and `x-expires`, and can even see the TTL values I specified, but don't see queue ever sticking around for the 30 minutes I specified.

**Comment by mookid8000** [comment]
I've never built anything into Rebus' RabbitMQ transport that deletes queues, so I think it's unlikely that something like that is happening.

Have you tried reproducing the behaviour without Rebus in the mix? Could be fun to see what would happen if you just coded it with raw RabbitMQ driver stuff.... 🤔

**Comment by jarikp** [comment]
Hi, I think I've found what is causing this problem. See suggested pull request.

**Comment by jarikp** [comment]
Hi @ronnyek 

I tried to unit tests, but some of this behavior is not deterministic, meaning that RMQ does not guaranty when exactly it will delete expired queues. Indeed, this is a bit confusing. As I read the docs for RMQ, there are following properties (https://www.rabbitmq.com/queues.html) related to this topic:

- auto-delete, meaning that queue will be deleted when its last consumer is cancelled or disconnected
- TTL (auto-expire, https://www.rabbitmq.com/ttl.html#queue-ttl), queue will be deleted, if unused for at least the expiration period

The auto-delete option is set explicitly when the queue is declared, whilst TTL is set through a client property **x-expires** argument.

The RMQ docs says that "No guarantee is given as to how promptly the queue will be removed after the expiration period has elapsed", this is why unit testing is a bit ugly and not reliable here.

But the problem which my PR address is not because of problems with RMQ, but due to a mistake in the code: if auto-delete is "false", then the property **x-expires** is never propagated to RMQ when a queue is created, which explains what you see in your application. A simple way to check this is to look for an EXP badge in the queue features:
![image](https://user-images.githubusercontent.com/45719768/63701919-3aa95880-c826-11e9-8af4-d2b8d9aea944.png)
the tooltip indicates the TTL in MS.

Hopefully, @mookid8000 will review and advise on how we can test this behavior in a proper way using the Rebus unit testing framework.

**Comment by jarikp** [comment]
then you can simple rewrite your code like this:
` .InputQueueOptions(o => o.SetAutoDelete(false, 1000)....`
into this
` .InputQueueOptions(o => o.SetAutoDelete(false).AddArgument("x-expires", 1000)...`

it will work as well, you don't have to wait for an update from Rebus.RabbitMQ
