### ISSUE TITLE
RPC

### ISSUE THREAD

**Issue by marrrschine** [rebus-org/Rebus.RabbitMq#64]
hi,

I have a question. 
Is there a way to [implement RPC](https://www.rabbitmq.com/tutorials/tutorial-six-dotnet.html) with Rebus? Thanks a lot!

**Comment by mookid8000** [comment]
Both yes and no 🙂 Rebus has the [Rebus.Async](https://github.com/rebus-org/Rebus.Async/) package, which enables writing code like this:
```csharp
var request = new SomeRequest();

var reply = await _bus.SendRequest<SomeReply>(request);

```

but you are advised to avoid using asynchronous durable message queues for this kind of communication as much as possible, because it's using an _asynchronous and durable middleware_ (i.e. message queues) to do something that is _synchronous and transient_ in nature, so it's 
* bloated
* overkill
* slow
* too safe
and so on.

I recommend using JSON over HTTP or gRPC for all of your RPC needs.

With that said, Rebus.Async can definitely also be used. Just be aware that there are better ways of doing synchronous RPC. 🙂
