### ISSUE TITLE
Get client certificate from Local Storage on Windows

### ISSUE THREAD

**Issue by zykindmitry** [rebus-org/Rebus.RabbitMq#87]
Hi!

I'm trying to run rebus with rabbitMQ transport with ssl auth on windows. I don't see a possibility to provide RabbitMQ client with X509Certificate object (the Certs collection of SslOption in the code below  is not populated):

            var sslOption = new SslOption(ssl.ServerName, ssl.CertPath, ssl.Enabled)
            {
                CertPassphrase = ssl.CertPassphrase,
                Version = ssl.Version,
                AcceptablePolicyErrors = ssl.AcceptablePolicyErrors
            };
Can you suggest any other way I can provide client certificate from a local storage on windows.

**Comment by StasD** [comment]
Hi,

Is this still not working?

I was only able to connect to RabbitMQ server after I set `ssl_options.fail_if_no_peer_cert = false` in `rabbitmq.conf`. When it's `true`, Rebus can't connect to it, and I'm getting  `no_client_certificate_provided` messages in RabbitMQ log.

Here is my code:


```
var certPaths = builder.Configuration.GetSection("Kestrel:Endpoints:Https:Certificate").Get<CertificatePaths>()!;
var certificate = X509Certificate2.CreateFromPemFile(certPaths.Path, certPaths.KeyPath);

var rabbitMqConnString = builder.Configuration.GetConnectionString("RabbitMQ") ?? throw new InvalidOperationException("Connection string 'RabbitMQ' not found.");

var rabbitMqUri = new Uri(rabbitMqConnString);

builder.Services.AddRebus((configure, provider) => configure
    .Transport(t =>
        t.UseRabbitMq(rabbitMqConnString, "kanbanboard-app-queue")
            // .CustomizeConnectionFactory(conn => {
            //     var cnn = (ConnectionFactory)conn;
            //     cnn.Uri = rabbitMqUri;
            //     cnn.Ssl.Certs = [certificate];
            //     return cnn;
            // })
        )
    .Outbox(o => o.StoreInPostgreSql(postgresConnString, "outbox")),
    //.Routing(c => c.TypeBased().Map<KanbanTaskChangedMessage>("kanbanboard-app-queue"))
    onCreated: async bus =>
    {
        await bus.Subscribe<KanbanTaskChangedMessage>();
    }
);

builder.Services.AutoRegisterHandlersFromAssemblyOf<Program>();

```

The `CustomizeConnectionFactory` code is currenly commented out (because with `ssl_options.fail_if_no_peer_cert = false` everything works with or without it), but if I enable it and set a breakpoint at `return cnn;` line, the `cnn` object looks ok to me.

~~BTW, I can't get "Outbox" functionality working, too, but that's another topic.~~ (Figured out how to use Outbox :))

**Comment by mookid8000** [comment]
Hi @StasD , have you figured out what was wrong?

**Comment by StasD** [comment]
Hi @mookid8000 ,

Yes, I have. In the [ConnectionManager.cs](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/Internals/ConnectionManager.cs) file, you have two constructors which set `_connectionFactory` and `_amqpTcpEndpoints` fields. Then in `GetConnectionAsync` method you create connection like this:
```
                _activeConnection = await _connectionFactory.CreateConnectionAsync(
                    endpoints: _amqpTcpEndpoints,
                    clientProvidedName: _clientProvidedName,
                    cancellationToken: cancellationToken
                );

                return _activeConnection;
```
The issue is that all the Ssl related settings of `_connectionFactory` (configured in `CustomizeConnectionFactory()`) are ignored inside this overload of `.CreateConnectionAsync` method, just as noted in the [above post](https://github.com/rebus-org/Rebus.RabbitMq/issues/87#issuecomment-950883045). So you probably should either use an overload with `hostnames`, as I did (see below), or incorporate these setting in `_amqpTcpEndpoints` (but `hostnames` overload essentially does that).

I managed to make it work, though, by using my own class that implements `IConnectionFactory`. For most of the methods, it simply calls `RabbitMQ.Client.ConnectionFactory` implementation, but for `CreateConnectionAsync(IEnumerable<AmqpTcpEndpoint> endpoints, ...` methods I call `CreateConnectionAsync(IEnumerable<string> hostnames, ...` overloads, getting `hostnames` from `endpoints` like this `endpoints.Select(endpoint => endpoint.HostName)`. Overloads with `hostnames` use Ssl settings configured in `CustomizeConnectionFactory()` just fine. You can take a look at my current code [here](https://github.com/StasD/KanbanBoard) (the relevant files are [Program.cs](https://github.com/StasD/KanbanBoard/blob/main/KanbanBoardApi/Program.cs) and [RabbitMQConnectionFactory.cs](https://github.com/StasD/KanbanBoard/blob/main/KanbanBoardApi/Common/RabbitMQConnectionFactory.cs)).
